export const categoryButtonData = [
  { name: 'All Types' },
  { name: 'Long dresses' },
  { name: 'Ankara wax prints' },
  { name: 'Short dresses' },
  { name: 'Mid-length dresses' },
  { name: 'Hanging drops earrings' },
  { name: 'Wigs' },
  { name: 'Jumpsuits and Overalls' },
  { name: 'Suits' },
  { name: '2 pieces set' },
  { name: 'Waist chain, bine-bine' },
  { name: 'Sandals, flip flops' },
  { name: 'Men Traditional clothings' },
  { name: 'Kimons' },
  { name: 'Hand bags' },
  { name: 'Rings' },
  { name: 'T-shirts' },
  { name: 'Mid-long necklaces' },
  { name: 'Spices, Plants, Roots and Powders' },
  { name: 'Headwraps' },
  { name: 'Traditional Clothings' },
  { name: 'Large hoop and ring earrings' },
  { name: 'Crew necklaces' },
  { name: 'Bombers' },
  { name: 'Tunics' },
  { name: 'Jewelry Sets' },
  { name: 'Cuff bracelets' },
  { name: 'Men Tunics' },
  { name: "Men's T-shirts" },
  { name: 'Dresses and Girl Sets' },
  { name: 'Kente' },
  { name: 'Maxi skirts' },
  { name: 'Bikinis' },
  { name: 'Adire, Indigo and Batik' },
];
