const languageNames = new Intl.DisplayNames(['en'], { type: 'region' });

export const sortFilterData = [
  {
    category_name: 'Sort by',
    links: [
      'Popularity',
      'New In',
      'Lowest Price',
      'Highest Price',
      'Highest Discount',
    ],
  },
  {
    category_name: 'Women size',
    links: ['XXS - Women', 'XS - Women', 'S - Women', 'M - Women', 'L - Women'],
  },
  {
    category_name: 'Babies size',
    links: [
      '12 - Months',
      '6 - Months',
      '9 - Months',
      '24 - Months',
      '18 - Months',
      '3 - Months',
      '1 - Months',
      '2 - Months',
    ],
  },
  {
    category_name: 'Men size',
    links: ['XXS - Men', 'XS - Men', 'S - Men', 'M - Men', 'L - Men'],
  },
  {
    category_name: 'Kids size',
    links: [
      '1 - years',
      '2 - years',
      '3 - years',
      '4 - years',
      '5 - years',
      '6 - years',
      '8 - years',
      '10 - years',
      '12 - years',
      '14 - years',
      '16 - years',
    ],
  },
  {
    category_name: 'Shoes size F',
    links: [
      'Eu 38 - US 6.5 - UK 5',
      'US 8 - UK 6 EU 38.5',
      'US 7.5 - UK 5.5 EU 38',
      'US 8.5 - UK 6.5 EU 39',
      'US 10.5 - UK 8.5 EU 41',
      'US 9.5 - UK 7.5 EU 40',
      'US 6 - UK 3.5 EU 36',
      'US 7 - UK 5 EU 37.5',
      'US 5 - UK 3 EU 35.5',
      'US 9 - UK 7 EU 39.5',
      'US 11.5 - UK 9.5 EU 42',
      'US 11 - UK 9 EU 41.5',
      'US 10 - UK 8 EU 40.5',
      'US 12 - UK 10 EU 43',
      'US 13 - UK 11 EU 44',
      'US 4.5 - UK 2.5 EU 35',
      'US 4 - UK 2 EU 34',
      'US 16 - UK Kid 0.5 EU Kid 0.5',
      'US 17 - UK Kid 1.5 EU Kid 1',
      'US 18 - UK Kid 3 EU Kid 2',
      'US 19 - UK Kid 4 EU Kid 3',
    ],
  },
  {
    category_name: 'Bras size',
    links: [
      'eu-95b-us-36b-uk-36b',
      'eu-95d-us-36d-uk-36d',
      'eu-100c-us-38c-uk-38c',
      'eu-85b-us-32b-uk-32b',
      'eu-85c-us-32c-uk-32c',
      'eu-85d-us-32d-uk-32d',
      'eu-90b-us-34b-uk-34b',
      'eu-90c-us-34c-uk-34c',
      'eu-90d-us-34d-uk-34d',
      'eu-95c-us-36c-uk-36c',
      'eu-110c-us-42c-uk-42c',
      'eu-85a-us-32a-uk-32a',
      'eu-90a-us-34a-uk-34a',
      'eu-95a-us-36a-uk-36a',
      'eu-100a-us-38a-uk-38a',
      'eu-100b-us-38b-uk-38b',
      'eu-100d-us-38d-uk-38d',
      'eu-100e-us-38dd-uk-38dd',
      'eu-100f-us-38ddd-uk-38e',
      'eu-100g-us-38g-uk-38f',
      'eu-100h-us-38h-uk-38ff',
      'eu-105a-us-40a-uk-40a',
      'eu-105b-us-40b-uk-40b',
      'eu-105c-us-40c-uk-40c',
      'eu-105d-us-40d-uk-40d',
      'eu-105e-us-40dd-uk-40dd',
      'eu-105f-us-40ddd-uk-40e',
      'eu-105g-us-40g-uk-40f',
      'eu-105h-us-40h-uk-40ff',
      'eu-110a-us-42a-uk-42a',
      'eu-110b-us-42b-uk-42b',
      'eu-110d-us-42d-uk-42d',
      'eu-110e-us-42dd-uk-42dd',
      'eu-110f-us-42ddd-uk-42e',
      'eu-110g-us-42g-uk-42f',
      'eu-110h-us-42h-uk-42ff',
      'eu-115a-us-44a-uk-44a',
      'eu-115b-us-44b-uk-44b',
      'eu-115c-us-44c-uk-44c',
      'eu-115d-us-44d-uk-44d',
      'eu-115e-us-44dd-uk-44dd',
      'eu-115f-us-44ddd-uk-44e',
      'eu-115g-us-44g-uk-44f',
      'eu-115h-us-44h-uk-44ff',
      'eu-75a-us-28a-uk-28a',
      'eu-75b-us-28b-uk-28b',
      'eu-75c-us-28c-uk-28c',
      'eu-75d-us-28d-uk-28d',
      'eu-75e-us-28dd-uk-28dd',
      'eu-75f-us-28ddd-uk-28e',
      'eu-75g-us-28g-uk-28f',
      'eu-75h-us-28h-uk-28ff',
      'eu-80a-us-30a-uk-30a',
      'eu-80b-us-30b-uk-30b',
      'eu-80c-us-30c-uk-30c',
      'eu-80d-us-30d-uk-30d',
      'eu-80e-us-30dd-uk-30dd',
      'eu-80f-us-30ddd-uk-30e',
      'eu-80g-us-30g-uk-30f',
      'eu-80h-us-30h-uk-30ff',
      'eu-85e-us-32dd-uk-32dd',
      'eu-85f-us-32ddd-uk-32e',
      'eu-85g-us-32g-uk-32f',
      'eu-85h-us-32h-uk-32ff',
      'eu-90e-us-34dd-uk-34dd',
      'eu-90f-us-34ddd-uk-34e',
      'eu-90g-us-34g-uk-34f',
      'eu-90h-us-34h-uk-34ff',
      'eu-95e-us-36dd-uk-36dd',
      'eu-95f-us-36ddd-uk-36e',
      'eu-95g-us-36g-uk-36f',
      'eu-95h-us-36h-uk-36ff',
      'eu-95b-us-36b-uk-36b',
      'eu-95d-us-36d-uk-36d',
      'eu-100c-us-38c-uk-38c',
      'eu-85b-us-32b-uk-32b',
      'eu-85c-us-32c-uk-32c',
      'eu-85d-us-32d-uk-32d',
      'eu-90b-us-34b-uk-34b',
      'eu-90c-us-34c-uk-34c',
      'eu-90d-us-34d-uk-34d',
      'eu-95c-us-36c-uk-36c',
      'eu-110c-us-42c-uk-42c',
      'eu-85a-us-32a-uk-32a',
      'eu-90a-us-34a-uk-34a',
      'eu-95a-us-36a-uk-36a',
      'eu-100a-us-38a-uk-38a',
      'eu-100b-us-38b-uk-38b',
      'eu-100d-us-38d-uk-38d',
      'eu-100e-us-38dd-uk-38dd',
      'eu-100f-us-38ddd-uk-38e',
      'eu-100g-us-38g-uk-38f',
      'eu-100h-us-38h-uk-38ff',
      'eu-105a-us-40a-uk-40a',
      'eu-105b-us-40b-uk-40b',
      'eu-105c-us-40c-uk-40c',
      'eu-105d-us-40d-uk-40d',
      'eu-105e-us-40dd-uk-40dd',
      'eu-105f-us-40ddd-uk-40e',
      'eu-105g-us-40g-uk-40f',
      'eu-105h-us-40h-uk-40ff',
      'eu-110a-us-42a-uk-42a',
      'eu-110b-us-42b-uk-42b',
      'eu-110d-us-42d-uk-42d',
      'eu-110e-us-42dd-uk-42dd',
      'eu-110f-us-42ddd-uk-42e',
      'eu-110g-us-42g-uk-42f',
      'eu-110h-us-42h-uk-42ff',
      'eu-115a-us-44a-uk-44a',
      'eu-115b-us-44b-uk-44b',
      'eu-115c-us-44c-uk-44c',
      'eu-115d-us-44d-uk-44d',
      'eu-115e-us-44dd-uk-44dd',
      'eu-115f-us-44ddd-uk-44e',
      'eu-115g-us-44g-uk-44f',
      'eu-115h-us-44h-uk-44ff',
      'eu-75a-us-28a-uk-28a',
      'eu-75b-us-28b-uk-28b',
      'eu-75c-us-28c-uk-28c',
      'eu-75d-us-28d-uk-28d',
      'eu-75e-us-28dd-uk-28dd',
      'eu-75f-us-28ddd-uk-28e',
      'eu-75g-us-28g-uk-28f',
      'eu-75h-us-28h-uk-28ff',
      'eu-80a-us-30a-uk-30a',
      'eu-80b-us-30b-uk-30b',
      'eu-80c-us-30c-uk-30c',
      'eu-80d-us-30d-uk-30d',
      'eu-80e-us-30dd-uk-30dd',
      'eu-80f-us-30ddd-uk-30e',
      'eu-80g-us-30g-uk-30f',
      'eu-80h-us-30h-uk-30ff',
      'eu-85e-us-32dd-uk-32dd',
      'eu-85f-us-32ddd-uk-32e',
      'eu-85g-us-32g-uk-32f',
      'eu-85h-us-32h-uk-32ff',
      'eu-90e-us-34dd-uk-34dd',
      'eu-90f-us-34ddd-uk-34e',
      'eu-90g-us-34g-uk-34f',
      'eu-90h-us-34h-uk-34ff',
      'eu-95e-us-36dd-uk-36dd',
      'eu-95f-us-36ddd-uk-36e',
      'eu-95g-us-36g-uk-36f',
      'eu-95h-us-36h-uk-36ff',
    ],
  },
  {
    category_name: 'Shoes size M',
    links: [
      'us-9-uk-8-5-eu-42',
      'us-11-uk-10-5-eu-44',
      'us-10-uk-9-5-eu-43',
      'us-12-uk-11-5-eu-45',
      'us-7-5-uk-7-eu-40',
      'us-8-5-uk-8-eu-41',
      'us-13-uk-12-5-eu-46',
      'us-6-uk-5-5-eu-39',
      'us-14-uk-13-5-eu-47',
      'us-15-uk-14-5-eu-48',
      'us-10-5-uk-10-eu-43-5',
      'us-9-5-uk-9-eu-42-5',
      'us-11-5-uk-11-eu-44-5',
      'us-7-5-uk-7-eu-40-5',
      'us-8-5-uk-8-eu-41-5',
      'us-5-5-uk-5-eu-38-5',
      'us-6-5-uk-6-eu-39-5',
      'us-9-uk-8-5-eu-42',
      'us-11-uk-10-5-eu-44',
      'us-10-uk-9-5-eu-43',
      'us-12-uk-11-5-eu-45',
      'us-7-5-uk-7-eu-40',
      'us-8-5-uk-8-eu-41',
      'us-13-uk-12-5-eu-46',
      'us-6-uk-5-5-eu-39',
      'us-14-uk-13-5-eu-47',
      'us-15-uk-14-5-eu-48',
      'us-10-5-uk-10-eu-43-5',
      'us-9-5-uk-9-eu-42-5',
      'us-11-5-uk-11-eu-44-5',
      'us-7-5-uk-7-eu-40-5',
      'us-8-5-uk-8-eu-41-5',
      'us-5-5-uk-5-eu-38-5',
      'us-6-5-uk-6-eu-39-5',
    ],
  },
  {
    category_name: 'Kids Shoes sizes',
    links: [
      'eu-16-us-kid-0-5-uk-kid-0-5',
      'eu-17-us-kid-1-5-uk-kid-1',
      'eu-18-us-kid-3-uk-kid-2',
      'eu-19-us-kid-4-uk-kid-3',
      'eu-20-us-kid-4-5-uk-kid-3-5',
      'eu-21-us-kid-5-5-uk-kid-4-5',
      'eu-22-us-kids-6-uk-kids-5',
      'eu-23-us-kids-7-uk-kids-6',
      'eu-24-us-kids-8-uk-kids-7',
      'eu-25-us-kids-9-uk-kids-8',
      'eu-26-us-kids-9-5-uk-kids-8-5',
      'eu-27-us-kids-10-uk-kids-9',
      'eu-28-us-kids-11-uk-kids-10',
      'eu-29-us-kids-11-5-uk-kids-10-5',
      'eu-30-us-kids-12-uk-kids-11',
      'eu-31-us-kids-13-uk-kids-12',
      'eu-32-us-big-kid-1-uk-kid-13',
      'eu-33-us-big-kid-1-5-uk-kid-13-5',
      'eu-16-us-kid-0-5-uk-kid-0-5',
      'eu-17-us-kid-1-5-uk-kid-1',
      'eu-18-us-kid-3-uk-kid-2',
      'eu-19-us-kid-4-uk-kid-3',
      'eu-20-us-kid-4-5-uk-kid-3-5',
      'eu-21-us-kid-5-5-uk-kid-4-5',
      'eu-22-us-kids-6-uk-kids-5',
      'eu-23-us-kids-7-uk-kids-6',
      'eu-24-us-kids-8-uk-kids-7',
      'eu-25-us-kids-9-uk-kids-8',
      'eu-26-us-kids-9-5-uk-kids-8-5',
      'eu-27-us-kids-10-uk-kids-9',
      'eu-28-us-kids-11-uk-kids-10',
      'eu-29-us-kids-11-5-uk-kids-10-5',
      'eu-30-us-kids-12-uk-kids-11',
      'eu-31-us-kids-13-uk-kids-12',
      'eu-32-us-big-kid-1-uk-kid-13',
      'eu-33-us-big-kid-1-5-uk-kid-13-5',
    ],
  },
  {
    category_name: 'Fit',
    links: [
      'babydoll-dresses',
      'beach-dresses-cover-ups',
      'beach-shorts',
      'beach-skirts',
      'bodycon-dresses',
      'bodycon-skirts',
      'business-dresses',
      'casual-dresses',
      'cropped-pants',
      'evening-dresses-cocktail',
      'flared-dresses',
      'flared-pants-and-bootcut',
      'flared-skirts',
      'high-waist-pants',
      'high-waist-skirts',
      'jeans',
      'maternity-dresses',
      'maxi-dresses',
      'maxi-skirts',
      'none',
      'pencil-skirts',
      'pleated-skirts',
      'regular-fit',
      'sarouel-dresses',
      'shirt-dresses',
      'slim-fit',
      'slim-straight-pants',
      'straight-dresses',
      'straight-skirts',
      'sundresses',
      'sweater-dresses',
      't-shirt-dresses',
      'wedding-dress',
      'wrap-dressses',
      'wrap-skirts',
      'babydoll-dresses',
      'beach-dresses-cover-ups',
      'beach-shorts',
      'beach-skirts',
      'bodycon-dresses',
      'bodycon-skirts',
      'business-dresses',
      'casual-dresses',
      'cropped-pants',
      'evening-dresses-cocktail',
      'flared-dresses',
      'flared-pants-and-bootcut',
      'flared-skirts',
      'high-waist-pants',
      'high-waist-skirts',
      'jeans',
      'maternity-dresses',
      'maxi-dresses',
      'maxi-skirts',
      'none',
      'pencil-skirts',
      'pleated-skirts',
      'regular-fit',
      'sarouel-dresses',
      'shirt-dresses',
      'slim-fit',
      'slim-straight-pants',
      'straight-dresses',
      'straight-skirts',
      'sundresses',
      'sweater-dresses',
      't-shirt-dresses',
      'wedding-dress',
      'wrap-dressses',
      'wrap-skirts',
    ],
  },
  {
    category_name: 'Earings',
    links: ['pierced-earrings', 'balls-ear-clips', 'pierced-earrings'],
  },
  {
    category_name: 'Country',
    links: [
      languageNames.of('AE'),
      languageNames.of('AO'),
      languageNames.of('AT'),
      languageNames.of('AU'),
      languageNames.of('BE'),
      languageNames.of('BF'),
      languageNames.of('BI'),
      languageNames.of('BJ'),
      languageNames.of('BR'),
      languageNames.of('BW'),
      languageNames.of('CA'),
      languageNames.of('CD'),
      languageNames.of('CF'),
      languageNames.of('CG'),
      languageNames.of('CH'),
      languageNames.of('CI'),
      languageNames.of('CL'),
      languageNames.of('CM'),
      languageNames.of('CN'),
      languageNames.of('CV'),
      languageNames.of('CZ'),
      languageNames.of('DE'),
      languageNames.of('DK'),
      languageNames.of('DZ'),
      languageNames.of('EG'),
      languageNames.of('ES'),
      languageNames.of('ET'),
      languageNames.of('FI'),
      languageNames.of('FR'),
      languageNames.of('GA'),
      languageNames.of('GB'),
      languageNames.of('GF'),
      languageNames.of('GH'),
      languageNames.of('GM'),
      languageNames.of('GN'),
      languageNames.of('GP'),
      languageNames.of('GQ'),
      languageNames.of('GR'),
      languageNames.of('HT'),
      languageNames.of('HU'),
      languageNames.of('ID'),
      languageNames.of('IE'),
      languageNames.of('IN'),
      languageNames.of('IT'),
      languageNames.of('JM'),
      languageNames.of('KE'),
      languageNames.of('KP'),
      languageNames.of('LB'),
      languageNames.of('LT'),
      languageNames.of('LU'),
      languageNames.of('MA'),
      languageNames.of('MG'),
      languageNames.of('ML'),
      languageNames.of('MQ'),
      languageNames.of('MT'),
      languageNames.of('MU'),
      languageNames.of('MW'),
      languageNames.of('MX'),
      languageNames.of('MY'),
      languageNames.of('MZ'),
      languageNames.of('NE'),
      languageNames.of('NG'),
      languageNames.of('NL'),
      languageNames.of('NO'),
      languageNames.of('NZ'),
      languageNames.of('PF'),
      languageNames.of('PK'),
      languageNames.of('PL'),
      languageNames.of('PT'),
      languageNames.of('RE'),
      languageNames.of('RU'),
      languageNames.of('RW'),
      languageNames.of('SE'),
      languageNames.of('SG'),
      languageNames.of('SI'),
      languageNames.of('SN'),
      languageNames.of('SX'),
      languageNames.of('SZ'),
      languageNames.of('TG'),
      languageNames.of('TH'),
      languageNames.of('TN'),
      languageNames.of('TR'),
      languageNames.of('TT'),
      languageNames.of('TZ'),
      languageNames.of('UG'),
      languageNames.of('US'),
      languageNames.of('VE'),
      languageNames.of('VN'),
      languageNames.of('ZA'),
      languageNames.of('ZM'),
      languageNames.of('ZW'),
      languageNames.of('AE'),
      languageNames.of('AO'),
      languageNames.of('AT'),
      languageNames.of('AU'),
      languageNames.of('BE'),
      languageNames.of('BF'),
      languageNames.of('BI'),
      languageNames.of('BJ'),
      languageNames.of('BR'),
      languageNames.of('BW'),
      languageNames.of('CA'),
      languageNames.of('CD'),
      languageNames.of('CF'),
      languageNames.of('CG'),
      languageNames.of('CH'),
      languageNames.of('CI'),
      languageNames.of('CL'),
      languageNames.of('CM'),
      languageNames.of('CN'),
      languageNames.of('CV'),
      languageNames.of('CZ'),
      languageNames.of('DE'),
      languageNames.of('DK'),
      languageNames.of('DZ'),
      languageNames.of('EG'),
      languageNames.of('ES'),
      languageNames.of('ET'),
      languageNames.of('FI'),
      languageNames.of('FR'),
      languageNames.of('GA'),
      languageNames.of('GB'),
      languageNames.of('GF'),
      languageNames.of('GH'),
      languageNames.of('GM'),
      languageNames.of('GN'),
      languageNames.of('GP'),
      languageNames.of('GQ'),
      languageNames.of('GR'),
      languageNames.of('HT'),
      languageNames.of('HU'),
      languageNames.of('ID'),
      languageNames.of('IE'),
      languageNames.of('IN'),
      languageNames.of('IT'),
      languageNames.of('JM'),
      languageNames.of('KE'),
      languageNames.of('KP'),
      languageNames.of('LB'),
      languageNames.of('LT'),
      languageNames.of('LU'),
      languageNames.of('MA'),
      languageNames.of('MG'),
      languageNames.of('ML'),
      languageNames.of('MQ'),
      languageNames.of('MT'),
      languageNames.of('MU'),
      languageNames.of('MW'),
      languageNames.of('MX'),
      languageNames.of('MY'),
      languageNames.of('MZ'),
      languageNames.of('NE'),
      languageNames.of('NG'),
      languageNames.of('NL'),
      languageNames.of('NO'),
      languageNames.of('NZ'),
      languageNames.of('PF'),
      languageNames.of('PK'),
      languageNames.of('PL'),
      languageNames.of('PT'),
      languageNames.of('RE'),
      languageNames.of('RU'),
      languageNames.of('RW'),
      languageNames.of('SE'),
      languageNames.of('SG'),
      languageNames.of('SI'),
      languageNames.of('SN'),
      languageNames.of('SX'),
      languageNames.of('SZ'),
      languageNames.of('TG'),
      languageNames.of('TH'),
      languageNames.of('TN'),
      languageNames.of('TR'),
      languageNames.of('TT'),
      languageNames.of('TZ'),
      languageNames.of('UG'),
      languageNames.of('US'),
      languageNames.of('VE'),
      languageNames.of('VN'),
      languageNames.of('ZA'),
      languageNames.of('ZM'),
      languageNames.of('ZW'),
    ],
  },
  {
    category_name: 'Discount',
    links: [
      '10-20',
      '20-30',
      '30-50',
      '50-70',
      '70-100',
      '10-20',
      '20-30',
      '30-50',
      '50-70',
      '70-100',
    ],
  },
  {
    category_name: 'Color',
    links: [
      'beige',
      'black',
      'blonde',
      'blue',
      'brown',
      'burgundy',
      'clear',
      'gold',
      'green',
      'grey',
      'indigo',
      'kaki',
      'mauve',
      'multicolour',
      'orange',
      'pink',
      'purple',
      'red',
      'silver',
      'turquoise',
      'white',
      'yellow',
      'beige',
      'black',
      'blonde',
      'blue',
      'brown',
      'burgundy',
      'clear',
      'gold',
      'green',
      'grey',
      'indigo',
      'kaki',
      'mauve',
      'multicolour',
      'orange',
      'pink',
      'purple',
      'red',
      'silver',
      'turquoise',
      'white',
      'yellow',
    ],
  },
  {
    category_name: 'Style',
    links: [
      'all-ankara',
      'casual',
      'none',
      'sexy-clothes',
      'streetwear',
      'with-an-ankara-touch',
      'zulu-maasai-and-pearls',
      'all-ankara',
      'casual',
      'none',
      'sexy-clothes',
      'streetwear',
      'with-an-ankara-touch',
      'zulu-maasai-and-pearls',
    ],
  },
  {
    category_name: 'Occasion',
    links: [
      'activewear',
      'evening-wear',
      'new-birth',
      'none',
      'the-beautiful-days',
      'wedding-and-ceremony',
      'workwear',
      'activewear',
      'evening-wear',
      'new-birth',
      'none',
      'the-beautiful-days',
      'wedding-and-ceremony',
      'workwear',
    ],
  },
  {
    category_name: 'Range',
    links: [
      'maternity',
      'none',
      'petite',
      'plus-size-and-curves',
      'tall',
      'maternity',
      'none',
      'petite',
      'plus-size-and-curves',
      'tall',
    ],
  },
  {
    category_name: 'Fabric',
    links: [
      'african-inspired-chiffon',
      'african-inspired-silk',
      'ankara-wax',
      'batik',
      'bazin',
      'bogolan-mudcloth',
      'cowry',
      'dashiki-addis-abeba-angelina',
      'embroidery',
      'handpainted',
      'kente',
      'maasai',
      'madras',
      'mixed-print',
      'none',
      'precious-metals-gold-silver',
      'shweshwe',
      'african-inspired-chiffon',
      'african-inspired-silk',
      'ankara-wax',
      'batik',
      'bazin',
      'bogolan-mudcloth',
      'cowry',
      'dashiki-addis-abeba-angelina',
      'embroidery',
      'handpainted',
      'kente',
      'maasai',
      'madras',
      'none',
      'precious-metals-gold-silver',
      'shweshwe',
    ],
  },
  {
    category_name: 'Material',
    links: [
      'aluminum',
      'ankara',
      'batik',
      'bazin',
      'beads',
      'bogolan',
      'bones',
      'brass',
      'brocart',
      'bronze',
      'cardboard',
      'cashmere',
      'ceramic',
      'clay',
      'cloth',
      'coconut',
      'copper',
      'cotton',
      'cowries',
      'crepe',
      'crystal',
      'enamel',
      'fabric',
      'fiber',
      'fur',
      'gabardine',
      'gem',
      'glass',
      'glossy-paper',
      'gold',
      'handwoven-cotton',
      'hemp',
      'hessian',
      'horn',
      'iron',
      'jean',
      'kente',
      'lace',
      'leather',
      'leatherette',
      'line',
      'madras',
      'mesh',
      'metal',
      'minerals',
      'mousseline',
      'nacre',
      'nickel',
      'organic-fabrics',
      'organza',
      'paper',
      'pearls',
      'plastic',
      'platinum',
      'polyester',
      'porcelain',
      'prints',
      'pvc',
      'raphia',
      'rattan',
      'resin',
      'rubber',
      'satin',
      'seeds',
      'shell',
      'silk',
      'silver',
      'soapstone',
      'steel',
      'stone',
      'stretch',
      'textile',
      'titanium',
      'tweed',
      'vegetable-ivory',
      'veil',
      'velvet',
      'wood',
      'wool',
      'wool-super-100',
      'woven-cloth',
      'aluminum',
      'ankara',
      'batik',
      'bazin',
      'beads',
      'bogolan',
      'bones',
      'brass',
      'brocart',
      'bronze',
      'cardboard',
      'cashmere',
      'ceramic',
      'clay',
      'cloth',
      'coconut',
      'copper',
      'cotton',
      'cowries',
      'crepe',
      'crystal',
      'enamel',
      'fabric',
      'fiber',
      'fur',
      'gabardine',
      'gem',
      'glass',
      'glossy-paper',
      'gold',
      'handwoven-cotton',
      'hemp',
      'hessian',
      'horn',
      'iron',
      'jean',
      'kente',
      'lace',
      'leather',
      'leatherette',
      'line',
      'madras',
      'mesh',
      'metal',
      'minerals',
      'mousseline',
      'nacre',
      'nickel',
      'organic-fabrics',
      'organza',
      'paper',
      'pearls',
      'plastic',
      'platinum',
      'polyester',
      'porcelain',
      'prints',
      'pvc',
      'raphia',
      'rattan',
      'resin',
      'rubber',
      'satin',
      'seeds',
      'shell',
      'silk',
      'silver',
      'soapstone',
      'steel',
      'stone',
      'stretch',
      'textile',
      'titanium',
      'tweed',
      'vegetable-ivory',
      'veil',
      'velvet',
      'wood',
      'wool',
      'wool-super-100',
      'woven-cloth',
    ],
  },
  {
    category_name: 'Jewel Style',
    links: [
      'ankara-wax-look',
      'discreet-pieces',
      'non-fabric-pieces',
      'none',
      'statement-pieces',
      'ankara-wax-look',
      'discreet-pieces',
      'non-fabric-pieces',
      'none',
      'statement-pieces',
    ],
  },
  {
    category_name: 'Hair Length',
    links: ['long', 'mi-long', 'short', 'long', 'mi-long', 'short'],
  },
  {
    category_name: 'Wig Style',
    links: [
      'bang',
      'bob-cut',
      'braided',
      'curly',
      'pixie',
      'straight',
      'wavy',
      'bang',
      'bob-cut',
      'braided',
      'curly',
      'pixie',
      'straight',
      'wavy',
    ],
  },
  {
    category_name: 'Head Size',
    links: ['average', 'large', 'small', 'average', 'large', 'small'],
  },
  {
    category_name: 'Type of hair accessories',
    links: [
      'brushes-combs',
      'elastics-barrettes',
      'hair-bonnet-towel',
      'hair-clipper',
      'others',
      'straightener-curling-iron',
      'brushes-combs',
      'elastics-barrettes',
      'hair-bonnet-towel',
      'hair-clipper',
      'others',
      'straightener-curling-iron',
    ],
  },
  {
    category_name: 'Scent',
    links: ['scented', 'unscented', 'scented', 'unscented'],
  },
  {
    category_name: 'Type of skin',
    links: [
      'combination',
      'dry',
      'normal',
      'oily',
      'sensitive',
      'combination',
      'dry',
      'normal',
      'oily',
      'sensitive',
    ],
  },
  {
    category_name: 'Concerns',
    links: [
      'acne-blemishes',
      'anti-aging',
      'blackheads',
      'dark-circles',
      'dryness',
      'dullness-uneven-texture',
      'fine-lines-wrinkles',
      'loss-of-firmness-elasticity',
      'oiliness',
      'pores',
      'puffiness',
      'redness',
      'stretch-marks',
      'acne-blemishes',
      'anti-aging',
      'blackheads',
      'dark-circles',
      'dryness',
      'dullness-uneven-texture',
      'fine-lines-wrinkles',
      'loss-of-firmness-elasticity',
      'oiliness',
      'pores',
      'puffiness',
      'redness',
      'stretch-marks',
    ],
  },
  {
    category_name: 'Types of spices',
    links: ['individual', 'mixed'],
  },
  {
    category_name: 'Shape',
    links: [
      'bicone',
      'coin',
      'donut',
      'floral',
      'heart',
      'other-polygons',
      'oval',
      'round',
      'square',
      'stars',
      'symbol',
      'teardrop',
      'triangle',
      'bicone',
      'coin',
      'donut',
      'floral',
      'heart',
      'other-polygons',
      'oval',
      'round',
      'square',
      'stars',
      'symbol',
      'teardrop',
      'triangle',
    ],
  },
];
